%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Users\Austin\Documents\GitHub\SpacecraftDesignFinn\TLEreader\TLE.txt
%
% Auto-generated by MATLAB on 02-Feb-2021 16:34:56

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["TLE", "for1", "ISS", "ZARYA", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["for1", "ISS", "ZARYA", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["for1", "ISS", "ZARYA", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9"], "EmptyFieldRule", "auto");

% Import the data
TLE1 = readtable("D:\Users\Austin\Documents\GitHub\SpacecraftDesignFinn\TLEreader\TLE.txt", opts);


%% Clear temporary variables
clear opts

% end autogenerated code
%% store orbital elements as variables, converting deg to rad as necessary

% grav parameter for Earth
mu = 3.986e14;

inc = str2double(TLE1{2,3})*pi/180;
raan = str2double(TLE1{2,4})*pi/180;
ecc = str2double("."+TLE1{2,5});
argperi = str2double(TLE1{2,6})*pi/180;
meananom = str2double(TLE1{2,7})*pi/180;
semi = (mu/(str2double(TLE1{2,8})*2*pi/86400)^2)^(1/3);